language: ruby
rvm:
  - 2.3.3
sudo: false
cache: bundler
only: master
env:
  matrix:
    - SOLIDUS_BRANCH=v1.0 DB=mysql
    - SOLIDUS_BRANCH=v1.0 DB=postgresql
    - SOLIDUS_BRANCH=v1.1 DB=mysql
    - SOLIDUS_BRANCH=v1.1 DB=postgresql
    - SOLIDUS_BRANCH=v1.2 DB=mysql
    - SOLIDUS_BRANCH=v1.2 DB=postgresql
