language: ruby
rvm:
  - 2.3.3
sudo: false
cache: bundler
only: master
env:
  matrix:
    - SOLIDUS_BRANCH=v1.3 DB=mysql
    - SOLIDUS_BRANCH=v1.3 DB=postgresql
    - SOLIDUS_BRANCH=v1.4 DB=mysql
    - SOLIDUS_BRANCH=v1.4 DB=postgresql
